version: 2
registries:
  docker-registry-registry-hub-docker-com:
    type: docker-registry
    url: https://registry.hub.docker.com

updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
    timezone: Europe/Paris
  target-branch: master
  reviewers:
  - marcmillien
  - mtparet
  registries:
  - docker-registry-registry-hub-docker-com
