version: 2

updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
    timezone: Europe/Paris
  target-branch: master
  reviewers:
  - marcmillien
  - mtparet
