version: 2.1
orbs:
  bot: lifen/bot@0

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.12
      - run: make build email=$EMAIL license=$LICENSE
      - run: make setup
      - run: make test email=$EMAIL license=$LICENSE
  build-and-push:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - run:
          name: Install git-lfs
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs fetch
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.12
      - run: make build email=$EMAIL license=$LICENSE
      - run: make push email=$EMAIL license=$LICENSE

workflows:
  version: 2
  build:
    jobs:
      - test:
          context: org-global
      - build-and-push:
          context: org-global
          filters:
            branches:
              only:
                - "master"
