version: 2.1
orbs:
  bot: lifen/bot@0

parameters:
  looker-version:
    type: string
    default: "25.10"

jobs:
  test:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: docker24
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: make build email=$EMAIL license=$LICENSE version=<< pipeline.parameters.looker-version >>
      - run: make setup
      - run: make test email=$EMAIL license=$LICENSE version=<< pipeline.parameters.looker-version >>
  build-and-push:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - run:
          name: Install git-lfs
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs fetch
      - run:
          name: Set LOOKER_VERSION
          command: |
            echo "export LOOKER_VERSION="$(make version email=$EMAIL license=$LICENSE version=<< pipeline.parameters.looker-version >>) >> "$BASH_ENV"
            source "$BASH_ENV"
            echo $LOOKER_VERSION
      - run: make download email=$EMAIL license=$LICENSE version=<< pipeline.parameters.looker-version >>
      - bot/docker-build-and-push:
          applicationName: looker
          dockerEngineVersion: docker24
          dockerBuildOptions: --build-arg EMAIL=$EMAIL --build-arg LICENSE=$LICENSE --build-arg LOOKER_VERSION=$LOOKER_VERSION
          dockerTag: $LOOKER_VERSION-$CIRCLE_SHA1

workflows:
  build:
    jobs:
      - test:
          context: org-global
      - build-and-push:
          context: org-global
          pre-steps:
            - checkout
            - bot/check-changed-files-or-halt:
                pattern: 'docker/'
          requires:
            - test
          filters:
            branches:
              only:
                - "master"

  daily_sast_scan: # DO NOT CHANGE THE WORKFLOW NAME
      triggers:
        - schedule:
            cron: "0 1 * * *"
            filters:
              branches:
                only:
                  - master
      jobs:
        - bot/sast:
            context: org-global

  sast_scan:
    jobs:
      - bot/sast:
          context: org-global
          filters:
            branches:
              ignore:
                - master
