#!/usr/bin/env ruby
# Download page https://download.looker.com/validate

require 'getoptlong'
require_relative 'common'

opts = GetoptLong.new(
  [ '--version', '-v', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--license', '-l', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--email', '-e', GetoptLong::REQUIRED_ARGUMENT ],
  [ '--no-cache', GetoptLong::NO_ARGUMENT ],
  [ '--help', GetoptLong::NO_ARGUMENT ],
)

def usage
  puts <<~EOF
    #{$PROGRAM_NAME} --version VERSION --license LICENSE --email EMAIL

    Example:
      #{$PROGRAM_NAME} --version 22.20 --license ABCD --email simon.fitoussi@lifen.fr
  EOF
  exit 0
end

version = nil
license = nil
email = nil
no_cache = false
opts.each do |opt, arg|
  case opt
  when '--help'
    usage
  when '--version'
    version = arg
  when '--license'
    license = arg
  when '--email'
    email = arg
  when '--no-cache'
    no_cache = true
  else
    puts "Unknown option !"
    usage
  end
end

usage if version.nil? || license.nil? || email.nil?

looker = Looker.new(version, license, email)
looker.clear_cache if no_cache
looker.download_jar
looker.download_jar_dependency
